t_scene_info = [
[cutscene_pause_sound, mus_Jamesoak],
[cutscene_create_textbox, "Edgar0.5"],
[cutscene_change_face, obj_player, LEFT],
[cutscene_move_char, obj_player, 96, 368, false, 1],
[cutscene_change_sprite_index, obj_Edgar, spr_EdgarR],
[cutscene_play_sound, mus_Nerdy_Annoyance, 1, true],
[cutscene_create_textbox, "Edgar1"],
[cutscene_quick_pause, mus_Nerdy_Annoyance],
[cutscene_play_sound, snd_AHWHAT, 1, false],
[cutscene_change_face, obj_player, SURP],
[cutscene_wait, 2],
[cutscene_change_face, obj_player, LEFT],
[cutscene_quick_resume, mus_Nerdy_Annoyance],
[cutscene_create_textbox, "Edgar1.2"],
[cutscene_stop_sound, mus_Nerdy_Annoyance],
[cutscene_resume_sound, mus_Jamesoak],
]